sources:
  airdrops_io:
    enabled: true
    mode: "list"
    urls:
      active: "https://airdrops.io/latest"
      upcoming: "https://airdrops.io/upcoming"
      ended: "https://airdrops.io/ended"

  airdrop_checklist:
    enabled: true
    mode: "list"
    urls:
      main: "https://airdropchecklist.com/"

  cmc_airdrops:
    enabled: true
    mode: "list"
    urls:
      main: "https://coinmarketcap.com/airdrop/"

  altcointrading_airdrops:
    enabled: false
    mode: "list"
    urls:
      main: "https://www.altcointrading.net/airdrops/"

  airdropsalert:
    enabled: false
    mode: "list"
    urls:
      main: "https://airdropsalert.com/"

  icomarks_airdrops:
    enabled: false
    mode: "list"
    urls:
      main: "https://icomarks.com/airdrops"

  earndrop:
    enabled: true
    mode: "wallet_tool"
    urls:
      main: "https://earndrop.io/"

  bankless_claimables:
    enabled: true
    mode: "wallet_tool"
    urls:
      main: "https://claimables.bankless.com"

